* Exercise 444

#+begin_quote
Exercise 443 means that the design for =gcd-structural= calls for some planning and a
design-by-composition approach.

The very explanation of "greatest common denominator" suggests a two-stage approach.
First design a function that can compute the list of divisors of a natural number.
Second, design a function that picks the largest common number in the list of divisors
of =n= and the list of divisors of =m=. The overall function would look like this:
#+end_quote

#+begin_src racket
(define (gcd-structural S L)
  (largest-common (divisors S S) (divisors S L)))

; N[>= 1] N[>= 1] -> [List-of N]
; computes the divisors of l smaller or equal to k
(define (divisors k l)
  '())

; [List-of N] [List-of N] -> N
; finds the largest number common to both k and l
(define (largest-common k l)
  1)
#+end_src

#+begin_quote
Why do you think divisors consumes two numbers? Why does it consume S as the first
argument in both cases?
#+end_quote

It consumes =l= since it is the number for which we'll produce divisors, and =k= since that'll be the starting candidate divisor which will drive the structural recursion. It consumes
=S= in both cases because the =gcd= of two numbers cannot be greater than the smaller of the two. In other words, this is equivalent to Figure 154's use of =min=.
