* Exercise 477

#+begin_quote
Inspect the function definition of arrangements in figure 171. The figure displays a
generative-recursive solution of the extended design problem covered by chapter 12.4,
namely

  given a word, create all possible rearrangements of the letters.

The extended exercise is a direct guide to the structurally recursive design of the main
function and two auxiliaries, where the design of the latter requires the creation of two
more helper functions. In contrast, figure 171 uses the power of generative
recursion—plus foldr and map—to define the same program as a single function definition.

Explain the design of the generative-recursive version of arrangments. Answer all
questions that the design recipe for generative recursion poses, including the question
of termination.

Does arrangements in figure 171 create the same lists as the solution
of chapter 12.4?
#+end_quote

#+begin_src racket
  ; [List-of X] -> [List-of [List-of X]]
  ; creates a list of all rearrangements of the items in w
  (define (arrangements w)
    (cond
      [(empty? w) '(())]
      [else
       (foldr (lambda (item others)
                (local ((define without-item
                          (arrangements (remove item w)))
                        (define add-item-to-front
                          (map (lambda (a) (cons item a))
                               without-item)))
                  (append add-item-to-front others)))
              '()
              w)]))

  (define (all-words-from-rat? w)
    (and (member (explode "rat") w)
         (member (explode "art") w)
         (member (explode "tar") w)))

  (check-satisfied (arrangements '("r" "a" "t"))
                   all-words-from-rat?)
#+end_src

* Explanation/Design Recipe Questions

1. What is a trivially solvable problem?
   Producing the arrangements for an empty word (i.e. the empty list)
2. How are trivial solutions solved?
   A list containing the empty list is returned.
3. How does the algorithm generate new problems that are more easily solvable than the original one? Is there one new problem that we generate or are there several?
   We generate one new problem: the problem of generating arrangements for the current word's letters, sans its first letter.
4. Is the solution of the given problem the same as the solution of (one of) the new problems? Or, do we need to combine the solutions to create a solution for the original problem? And, if so, do we need anything from the original problem data?
   It is not. To get the overall solution, we tack on the first letter of the word to the beginning of all the arrangements generated by the smaller problem.

* Does this version produce the same lists as the structural version?
It does, but in a different order.
